# Generated by Django 3.2.9 on 2022-02-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_image_productimage_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='photo',
            new_name='image',
        ),
    ]
