# Generated by Django 3.2.9 on 2022-02-19 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220217_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='sell',
            name='image',
        ),
        migrations.AddField(
            model_name='sell',
            name='images',
            field=models.ManyToManyField(to='service.SellImages'),
        ),
    ]
