# Generated by Django 3.2.9 on 2022-02-19 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20220219_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='images',
        ),
        migrations.AddField(
            model_name='sell',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.DeleteModel(
            name='SellImages',
        ),
    ]
