# Generated by Django 3.2.9 on 2022-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='you_are',
            field=models.CharField(choices=[(1, 'farmer'), (2, 'agrovet'), (3, 'industry_agent'), (4, 'marketer')], default=1, max_length=200),
        ),
    ]
